/// Flutter icons MyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const String iconPackage = 'MyIcons';

  static const _kFontFam = 'MyIcons';

  static const IconData colorize = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: iconPackage);
  static const IconData tune = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData toc = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData magic_wand = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData speaker_notes = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData verified_user = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData user_outline = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData all_inclusive = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData adjust = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData ac_unit = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData videogame_asset = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData games = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData gamepad = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData gradient = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData security = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData text_fields = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData fiber_new = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData dice = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData fire = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData fire_2 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData battery_charging_full = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData border_color = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData fire_station = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData edit_1 = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData feather = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData pencil_1 = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData pencil_2 = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData pencil_alt = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData note = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData minefield = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData color_adjust = const IconData(0xf020, fontFamily: _kFontFam);
  static const IconData certificate = const IconData(0xf0a3, fontFamily: _kFontFam);
  static const IconData magic = const IconData(0xf0d0, fontFamily: _kFontFam);
  static const IconData gamepad_1 = const IconData(0xf11b, fontFamily: _kFontFam);
  static const IconData shield = const IconData(0xf132, fontFamily: _kFontFam);
  static const IconData cube = const IconData(0xf1b2, fontFamily: _kFontFam);
  static const IconData user_secret = const IconData(0xf21b, fontFamily: _kFontFam);
  static const IconData first_order = const IconData(0xf2b0, fontFamily: _kFontFam);
  static const IconData fire_1 = const IconData(0xf525, fontFamily: _kFontFam);
}
